# Generated by Django 5.2 on 2026-04-23 06:37

import apps.core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Часовой пояс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'indexes': [models.Index(fields=['name'], name='core_compan_name_f8e523_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('employee', 'Сотрудник')], default='owner', max_length=20, verbose_name='Роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'abstract': False,
            },
            managers=[
                ('objects', apps.core.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.SlugField(blank=True, default='', verbose_name='Код')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.company')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrgRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, verbose_name='Код')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Уровень')),
                ('can_manage_permissions', models.BooleanField(default=False, verbose_name='Может управлять правами')),
                ('group', models.CharField(blank=True, default='', max_length=255, verbose_name='Группа')),
                ('is_assignable', models.BooleanField(default=True, verbose_name='Назначаема через UI')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная роль')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to='core.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='core.department')),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='core.orgrole')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.orgpermission')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Фамилия')),
                ('grade', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Грейд')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('revoked', 'Отозвано'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('org_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orgrole')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('grade', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Грейд')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='Аватар (URL)')),
                ('pattern', models.CharField(choices=[('5/2', '5/2'), ('2/2', '2/2'), ('flex', 'Гибкий')], default='flex', max_length=16, verbose_name='Паттерн работы')),
                ('can_split', models.BooleanField(default=False, verbose_name='Сплит-смены')),
                ('can_extra', models.BooleanField(default=True, verbose_name='Доп. смены')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('org_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.orgrole')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.company')),
            ],
            options={
                'verbose_name': 'Юнит',
                'verbose_name_plural': 'Юниты',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InviteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_assignments', to='core.department')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_assignments', to='core.invite')),
                ('org_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_assignments', to='core.orgrole')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_assignments', to='core.unit')),
            ],
            options={
                'verbose_name': 'Назначение приглашения',
                'verbose_name_plural': 'Назначения приглашений',
            },
        ),
        migrations.AddField(
            model_name='invite',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit'),
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.employee')),
                ('org_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.orgrole')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.unit')),
            ],
            options={
                'verbose_name': 'Назначение сотрудника',
                'verbose_name_plural': 'Назначения сотрудников',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.unit'),
        ),
        migrations.AddField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.unit'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.department')),
                ('org_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.orgrole')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
            },
        ),
        migrations.AddIndex(
            model_name='orgrole',
            index=models.Index(fields=['company', 'department'], name='core_orgrole_co_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='orgrole',
            index=models.Index(fields=['company', 'level'], name='core_orgrole_co_level_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orgrole',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['company', 'is_active'], name='core_unit_company_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='inviteassignment',
            unique_together={('invite', 'unit', 'org_role')},
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('company', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeassignment',
            unique_together={('employee', 'unit', 'org_role')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'grade'], name='core_employ_company_62e21c_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'unit'], name='core_dept_company_unit_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'unit', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('company', 'department', 'org_role', 'name')},
        ),
    ]
