# Generated by Django 5.2 on 2026-05-10 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.unit', verbose_name='Юнит'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='org_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.orgrole', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.unit', verbose_name='Юниты'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='org_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.orgrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.unit', verbose_name='Юнит'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL, verbose_name='Пригласил'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='org_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orgrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit', verbose_name='Юнит'),
        ),
        migrations.AlterField(
            model_name='inviteassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_assignments', to='core.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='inviteassignment',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_assignments', to='core.invite', verbose_name='Приглашение'),
        ),
        migrations.AlterField(
            model_name='inviteassignment',
            name='org_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_assignments', to='core.orgrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='inviteassignment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_assignments', to='core.unit', verbose_name='Юнит'),
        ),
        migrations.AlterField(
            model_name='orgrole',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='orgrole',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='core.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='orgrole',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='core.orgrole', verbose_name='Родительская роль'),
        ),
        migrations.AlterField(
            model_name='orgrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.orgpermission', verbose_name='Разрешения'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='org_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.orgrole', verbose_name='Роль'),
        ),
    ]
