# Generated by Django 5.2 on 2026-05-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgrole',
            name='is_admin_role',
            field=models.BooleanField(default=False, verbose_name='Административный функционал'),
        ),
    ]
