# Generated by Django 5.2 on 2026-04-23 06:37

import apps.textbooks.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория учебника',
                'verbose_name_plural': 'Категории учебников',
                'db_table': 'textbook_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTextbookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Модуль включён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_settings', to='core.company')),
            ],
            options={
                'verbose_name': 'Настройки учебников',
                'verbose_name_plural': 'Настройки учебников',
                'db_table': 'textbook_settings',
            },
        ),
        migrations.CreateModel(
            name='TextbookCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_cards', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='textbooks.textbookcategory')),
            ],
            options={
                'verbose_name': 'Карточка учебника',
                'verbose_name_plural': 'Карточки учебников',
                'db_table': 'textbook_cards',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CardPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=apps.textbooks.models.card_photo_upload_path)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='textbooks.textbookcard')),
            ],
            options={
                'verbose_name': 'Фото карточки',
                'verbose_name_plural': 'Фото карточек',
                'db_table': 'textbook_card_photos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CardParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_type', models.CharField(choices=[('front', 'Основной'), ('detail', 'Подробность')], default='front', max_length=10)),
                ('label', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.textbooks.models.paragraph_photo_upload_path)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='textbooks.textbookcard')),
            ],
            options={
                'verbose_name': 'Параграф карточки',
                'verbose_name_plural': 'Параграфы карточек',
                'db_table': 'textbook_card_paragraphs',
                'ordering': ['card', 'paragraph_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TextbookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_sections', to='core.company')),
                ('units', models.ManyToManyField(blank=True, related_name='textbook_sections', to='core.unit')),
            ],
            options={
                'verbose_name': 'Раздел учебника',
                'verbose_name_plural': 'Разделы учебников',
                'db_table': 'textbook_sections',
                'ordering': ['order', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='textbookcategory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='textbooks.textbooksection'),
        ),
        migrations.AddField(
            model_name='textbookcard',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='textbooks.textbooksection'),
        ),
        migrations.CreateModel(
            name='CardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='textbooks.textbookcard')),
            ],
            options={
                'verbose_name': 'Тег карточки',
                'verbose_name_plural': 'Теги карточек',
                'db_table': 'textbook_card_tags',
                'unique_together': {('card', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='CardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('org_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orgrole')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_assignments', to='core.unit')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='textbooks.textbookcard')),
            ],
            options={
                'verbose_name': 'Назначение карточки',
                'verbose_name_plural': 'Назначения карточек',
                'db_table': 'textbook_card_assignments',
                'constraints': [models.UniqueConstraint(fields=('card', 'unit', 'department', 'org_role'), name='unique_card_assignment', nulls_distinct=False)],
            },
        ),
        migrations.AlterUniqueTogether(
            name='textbookcategory',
            unique_together={('section', 'name')},
        ),
        migrations.AddIndex(
            model_name='textbookcard',
            index=models.Index(fields=['company', 'section', 'category'], name='textbook_ca_company_69519e_idx'),
        ),
    ]
