# Generated by Django 5.2 on 2026-05-07 05:34

import apps.textbooks.quiz_models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('textbooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('single', 'Один правильный'), ('multiple', 'Несколько правильных')], default='single', max_length=20, verbose_name='Тип')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('timer_seconds', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(60)], verbose_name='Таймер (сек)')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы тестов',
                'db_table': 'quiz_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн изучения')),
                ('attempt_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн прохождения')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='core.company', verbose_name='Компания')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_assignments', to='core.department', verbose_name='Подразделение')),
                ('org_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_assignments', to='core.orgrole', verbose_name='Должность')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='core.unit', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Назначение теста',
                'verbose_name_plural': 'Назначения тестов',
                'db_table': 'quiz_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершён (не пройден)'), ('passed', 'Пройден'), ('passed_with_flags', 'Пройден с замечаниями'), ('suspicious_attempt', 'Подозрительная попытка'), ('terminated_for_violation', 'Прекращён за нарушения'), ('expired', 'Истёк')], default='in_progress', max_length=30, verbose_name='Статус')),
                ('current_question_index', models.PositiveSmallIntegerField(default=0, verbose_name='Текущий индекс вопроса')),
                ('score_raw', models.PositiveSmallIntegerField(default=0, verbose_name='Правильных ответов')),
                ('score_pct', models.FloatField(blank=True, null=True, verbose_name='Результат (%)')),
                ('risk_score', models.FloatField(default=0.0, verbose_name='Risk score')),
                ('violation_count', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во нарушений')),
                ('total_hidden_ms', models.PositiveIntegerField(default=0, verbose_name='Суммарное время вне страницы (мс)')),
                ('question_order', models.JSONField(blank=True, default=list, verbose_name='Порядок вопросов')),
                ('server_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Серверный дедлайн')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='textbooks.quizassignment', verbose_name='Назначение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='core.company', verbose_name='Компания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='core.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки тестов',
                'db_table': 'quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(blank=True, default=list, verbose_name='Выбранные варианты (PK)')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Верно')),
                ('time_spent_ms', models.PositiveIntegerField(default=0, verbose_name='Время ответа (мс)')),
                ('timed_out', models.BooleanField(default=False, verbose_name='Время истекло')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='textbooks.quizattempt', verbose_name='Попытка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='textbooks.quizquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'db_table': 'quiz_attempt_answers',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='textbooks.quizquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'db_table': 'quiz_question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание материалов')),
                ('mode', models.CharField(choices=[('learning', 'Обучение'), ('exam', 'Экзамен')], default='exam', max_length=10, verbose_name='Режим')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('policy_config', models.JSONField(blank=True, default=dict, help_text='JSON с порогами античита.', verbose_name='Настройки античита')),
                ('pass_score_pct', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Порог прохождения (%)')),
                ('study_deadline_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Дней на изучение материалов')),
                ('attempt_deadline_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Дней на прохождение теста')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Перемешивать вопросы')),
                ('shuffle_options', models.BooleanField(default=False, verbose_name='Перемешивать варианты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_templates', to='core.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_templates', to='core.department', verbose_name='Подразделение')),
                ('org_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_templates', to='core.orgrole', verbose_name='Должность')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_templates', to='core.unit', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Шаблон теста',
                'verbose_name_plural': 'Шаблоны тестов',
                'db_table': 'quiz_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='textbooks.quiztemplate', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='quizassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='textbooks.quiztemplate', verbose_name='Шаблон теста'),
        ),
        migrations.CreateModel(
            name='QuizTemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to=apps.textbooks.quiz_models.quiz_file_upload_path, verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('image', 'Изображение'), ('other', 'Другое')], default='other', max_length=10, verbose_name='Тип файла')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='textbooks.quiztemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Файл теста',
                'verbose_name_plural': 'Файлы тестов',
                'db_table': 'quiz_template_files',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizTemplateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ссылки')),
                ('url', models.URLField(verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='textbooks.quiztemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Ссылка теста',
                'verbose_name_plural': 'Ссылки тестов',
                'db_table': 'quiz_template_links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizTemplateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_materials', to='textbooks.textbookcard', verbose_name='Карточка учебника (legacy)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_materials', to='textbooks.textbookcategory', verbose_name='Категория')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_materials', to='textbooks.textbooksection', verbose_name='Раздел')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='textbooks.quiztemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Материал теста',
                'verbose_name_plural': 'Материалы тестов',
                'db_table': 'quiz_template_materials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ViolationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_hidden', 'Вкладка скрыта'), ('tab_visible_return', 'Возврат на вкладку'), ('window_blur', 'Окно потеряло фокус'), ('window_focus', 'Окно получило фокус'), ('fullscreen_exit', 'Выход из полноэкранного режима')], max_length=30, verbose_name='Тип события')),
                ('occurred_at', models.DateTimeField(verbose_name='Время события')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Длительность (мс)')),
                ('risk_contribution', models.FloatField(default=0.0, verbose_name='Вклад в risk score')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='textbooks.quizattempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Событие нарушения',
                'verbose_name_plural': 'События нарушений',
                'db_table': 'quiz_violation_events',
                'ordering': ['occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['company', 'employee', 'status'], name='quiz_attemp_company_811ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['assignment', 'employee'], name='quiz_attemp_assignm_a368c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='quiztemplate',
            index=models.Index(fields=['company', 'unit'], name='quiz_templa_company_bc97f3_idx'),
        ),
        migrations.AddIndex(
            model_name='quiztemplate',
            index=models.Index(fields=['company', 'is_active'], name='quiz_templa_company_153da4_idx'),
        ),
        migrations.AddIndex(
            model_name='quizassignment',
            index=models.Index(fields=['company', 'unit'], name='quiz_assign_company_af30a6_idx'),
        ),
        migrations.AddIndex(
            model_name='quizassignment',
            index=models.Index(fields=['template', 'unit', 'department', 'org_role'], name='quiz_assign_templat_7eb9aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quiztemplatematerial',
            unique_together={('template', 'section', 'category')},
        ),
        migrations.AddIndex(
            model_name='violationevent',
            index=models.Index(fields=['attempt', 'event_type'], name='quiz_violat_attempt_480f86_idx'),
        ),
        migrations.AddIndex(
            model_name='violationevent',
            index=models.Index(fields=['attempt', 'occurred_at'], name='quiz_violat_attempt_b4936f_idx'),
        ),
    ]
