# Generated by Django 5.2 on 2026-05-10 17:02

import apps.textbooks.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_company_alter_department_unit_and_more'),
        ('textbooks', '0002_quiz_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='cardassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Назначил'),
        ),
        migrations.AlterField(
            model_name='cardassignment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='textbooks.textbookcard', verbose_name='Карточка'),
        ),
        migrations.AlterField(
            model_name='cardassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='cardassignment',
            name='org_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orgrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='cardassignment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_assignments', to='core.unit', verbose_name='Юнит'),
        ),
        migrations.AlterField(
            model_name='cardparagraph',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='textbooks.textbookcard', verbose_name='Карточка'),
        ),
        migrations.AlterField(
            model_name='cardparagraph',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='cardparagraph',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='cardparagraph',
            name='paragraph_type',
            field=models.CharField(choices=[('front', 'Основной'), ('detail', 'Подробность')], default='front', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='cardparagraph',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.textbooks.models.paragraph_photo_upload_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cardparagraph',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='cardphoto',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='textbooks.textbookcard', verbose_name='Карточка'),
        ),
        migrations.AlterField(
            model_name='cardphoto',
            name='file',
            field=models.ImageField(upload_to=apps.textbooks.models.card_photo_upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='cardphoto',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='cardphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружено'),
        ),
        migrations.AlterField(
            model_name='cardtag',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='textbooks.textbookcard', verbose_name='Карточка'),
        ),
        migrations.AlterField(
            model_name='cardtag',
            name='tag',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='textbookcard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='textbooks.textbookcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='textbookcard',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_cards', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='textbookcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='textbookcard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='textbookcard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='textbookcard',
            name='name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='textbookcard',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='textbookcard',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='textbooks.textbooksection', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='textbookcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='textbookcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='textbookcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='textbookcategory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='textbooks.textbooksection', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='textbooksection',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_sections', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='textbooksection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='textbooksection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='textbooksection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='textbooksection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='textbooksection',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='textbook_sections', to='core.unit', verbose_name='Юниты'),
        ),
    ]
