# Generated by Django 5.2 on 2026-05-10 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_company_alter_department_unit_and_more'),
        ('shop', '0003_refundrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shopitem',
            new_name='shop_items_company_f6cccf_idx',
            old_name='shop_items_company_f492c9_idx',
        ),
        migrations.AlterField(
            model_name='autoaccrualrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_accrual_rules', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='coinbalance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_balances', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='coinbalance',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_balance', to='core.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='core.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='shop.order', verbose_name='Связанный заказ'),
        ),
        migrations.AlterField(
            model_name='itemactivation',
            name='activated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата активации'),
        ),
        migrations.AlterField(
            model_name='itemactivation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_activations', to='core.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='itemactivation',
            name='purchased_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='shop.purchaseditem', verbose_name='Купленный товар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to='core.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.shopitem', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to='core.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_items', to='shop.shopitem', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to='shop.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='core.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='purchased_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='shop.purchaseditem', verbose_name='Купленный товар'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел'),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_categories', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_categories', to='core.unit', verbose_name='Юнит'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shop.shopcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='core.unit', verbose_name='Юнит'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
