# Generated by Django 5.2 on 2026-05-12 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_company_alter_department_unit_and_more'),
        ('shop', '0006_aml_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItemAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='Департамент')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shop.shopitem', verbose_name='Товар')),
                ('org_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orgrole', verbose_name='Должность')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_item_assignments', to='core.unit', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Назначение товара',
                'verbose_name_plural': 'Назначения товаров',
                'db_table': 'shop_item_assignments',
                'constraints': [models.UniqueConstraint(fields=('item', 'unit', 'department', 'org_role'), name='unique_shop_item_assignment', nulls_distinct=False)],
            },
        ),
    ]
