# Generated by Django 5.2 on 2026-05-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_is_admin_role_to_orgrole'),
        ('shop', '0007_shop_item_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_orders', to='core.employee', verbose_name='Получатель подарка'),
        ),
    ]
